let shopItemsData = [
  {
    id: "1",
    name: "Pc Portable Lenovo ",
    price: 645,
    desc: "IdeaPad 3 15IGL05 / Dual Core / 4 Go / Noir.",
    img: "images/1.png",
  },
  {
    id: "2",
    name: "Câble OTG Micro USB Mâle / USB Femelle",
    price: 1.5,
    desc: "Câble OTG - Connecteur Micro USB Mâle Vers USB Femelle",
    img: "images/&&.png",
  },
  {
    id: "3",
    name: "Référence : D611-BK",
    price: 8.2,
    desc: "LCasque avec micro Macro D611-Interface Jack 3.5-Serre tête réglable-Coussinets d'oreille en éponge douce.",
    img: "images/12.png",
  },
  {
    id: "4",
    name: "SOURIS FILAIRE SPIDER X2 / NOIR",
    price: 300,
    desc: "Souris Filaire Spider X2 - Technologie de connectivité : Filaire - Nombre de boutons : 3 - Interface avec l'ordinateur ",
    img: "images/21.png",
  },
  {
    id: "5",
    name: "PC PORTABLE MSI THIN GF63 12UCX / I5-12450H / RTX 2050 4G / 8 GO",
    price: 2265,
    desc: "Processeur Intel Core i5-12450H 12éme génération, up to 4.4 Ghz, 12 Mo de mémoire cache - Mémoire 8 Go DDR4-3200 MHz.",
    img: "images/pc.png",
  },
  {
    id: "6",
    name: "Écouteurs pour iPhone",
    price: 200,
    desc: "Branchez les écouteurs sur votre iPhone / iPad. Allez sur l'icône de réglage sur votre iPhone pour trouver Bluetooth et allumez-le.",
    img: "images/id.png",
  },
  {
    id: "7",
    name: "Pc Portable Lenovo V15 G4 AMN / AMD Dual Core / 8 Go",
    price: 450,
    desc: "Processeur AMD Athlon Silver 7120U, up to 3.5 Ghz, 3 Mo de cache",
    img: "images/pca.png",
  },
  {
    id: "8",
    name: " Le téléviseur LG 55C3 5 étoiles",
    price: 45,
    desc: "Les LG 55C2 et CS ont été une réussite en 2022 et leur successeur, le LG 55C3, — version 55 pouces (140 cm) du LG 65C3 que nous avons testé— ne devrait pas décevoir. ",
    img: "images/tv.png",
  },
  {
    id: "9",
    name: "Tablettes hybrides - Guide d'achat - UFC-Que Choisir",
    price: 85,
    desc: "est un ordinateur portable qui se présente sous la forme d'un mini ordinateur convertible avec clavier classique ou juste avec un écran tactile",
    img: "images/pcc.png",
  },
  {
    id: "10",
    name: "Ordinateur fixe",
    price: 120,
    desc: "C’est un ordinateur personnel destiné à être utilisé sur un bureau car l’ensemble est décomposé en plusieurs périphériques, ce qui rend plus compliqué de se déplacer avec.",
    img: "images/pc-fixe.png",
  },
  {
    id: "11",
    name: "ÉCOUTEURS SANS FIL TRUE WIRELESS - WHITE",
    price: 35,
    desc: "Pratiques et confortables à porter, ces écouteurs IPX5 résistent à la sueur et à l’eau; l’idéal pour faire son sport, aller à la plage.",
    img: "images/eco.png",
  },
  {
    id: "12",
    name: "Xiaomi : des PC portables RedmiBook 13, 14 et 16 pouces qui s'annoncent prometteurs",
    price: 350,
    desc: " Xiaomi a présenté une nouvelle gamme d'ordinateurs portables sous sa marque Redmi. Les RedmiBook 13, 14 et 16 misent sur un design minimaliste et une tarification a priori modérée compte tenu des caractéristiques techniques.",
    img: "images/pca.png",
  },
];
